package cr.ac.una.prograiv.project.domain;
// Generated 20/03/2018 10:03:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private Integer idPuesto;
     private Integer empresa;
     private String descripcion;
     private String sueldo;
     private String tipo;
     private int disponible;
     
    public Puesto() {
    }

	
    public Puesto(Integer empresa, String descripcion, String sueldo, String tipo, int disponible) {
        this.empresa = empresa;
        this.descripcion = descripcion;
        this.sueldo = sueldo;
        this.tipo = tipo;
        this.disponible = disponible;
    }
    
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }
    public Integer getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Integer empresa) {
        this.empresa = empresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(String sueldo) {
        this.sueldo = sueldo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(int disponible) {
        this.disponible = disponible;
    }


}


