package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2018 12:22:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carateristicas generated by hbm2java
 */
public class Carateristicas  implements java.io.Serializable {


     private Integer idCarateristicas;
     private String descripcion;
     private int padre;
     
    public Carateristicas() {
    }

	
    public Carateristicas(String descripcion, int padre) {
        this.descripcion = descripcion;
        this.padre = padre;
    }
    
    public Integer getIdCarateristicas() {
        return this.idCarateristicas;
    }
    
    public void setIdCarateristicas(Integer idCarateristicas) {
        this.idCarateristicas = idCarateristicas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPadre() {
        return this.padre;
    }
    
    public void setPadre(int padre) {
        this.padre = padre;
    }
    



}


