package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2018 12:22:08 PM by Hibernate Tools 4.3.1



/**
 * Carateristicaspuesto generated by hbm2java
 */
public class Carateristicaspuesto  implements java.io.Serializable {


     private Integer id;
     private Carateristicas carateristicas;
     private Puesto puesto;
     private String nivel;

    public Carateristicaspuesto() {
    }

	
    public Carateristicaspuesto(Carateristicas carateristicas, Puesto puesto) {
        this.carateristicas = carateristicas;
        this.puesto = puesto;
    }
    public Carateristicaspuesto(Carateristicas carateristicas, Puesto puesto, String nivel) {
       this.carateristicas = carateristicas;
       this.puesto = puesto;
       this.nivel = nivel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carateristicas getCarateristicas() {
        return this.carateristicas;
    }
    
    public void setCarateristicas(Carateristicas carateristicas) {
        this.carateristicas = carateristicas;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


