package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2018 12:22:08 PM by Hibernate Tools 4.3.1



/**
 * Carateristicasoferente generated by hbm2java
 */
public class Carateristicasoferente  implements java.io.Serializable {


     private Integer id;
     private Carateristicas carateristicas;
     private Oferente oferente;
     private String nivel;

    public Carateristicasoferente() {
    }

	
    public Carateristicasoferente(Carateristicas carateristicas, Oferente oferente) {
        this.carateristicas = carateristicas;
        this.oferente = oferente;
    }
    public Carateristicasoferente(Carateristicas carateristicas, Oferente oferente, String nivel) {
       this.carateristicas = carateristicas;
       this.oferente = oferente;
       this.nivel = nivel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carateristicas getCarateristicas() {
        return this.carateristicas;
    }
    
    public void setCarateristicas(Carateristicas carateristicas) {
        this.carateristicas = carateristicas;
    }
    public Oferente getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Oferente oferente) {
        this.oferente = oferente;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


