package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2018 12:22:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oferente generated by hbm2java
 */
public class Oferente  implements java.io.Serializable {


     private Integer idOferente;
     private Usuario usuario;
     private String cedula;
     private String nombre;
     private String primerApellido;
     private String nacionalidad;
     private String telefono;
     private String email;
     private String lactitud;
     private String longitud;
     private int contratado;
     private String direccion;
     private byte[] curriculum;
     private Set carateristicasoferentes = new HashSet(0);
     private Set puestooferentes = new HashSet(0);

    public Oferente() {
    }

	
    public Oferente(Usuario usuario, String cedula, String nombre, String primerApellido, String nacionalidad, String telefono, String email, String lactitud, String longitud, int contratado) {
        this.usuario = usuario;
        this.cedula = cedula;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.nacionalidad = nacionalidad;
        this.telefono = telefono;
        this.email = email;
        this.lactitud = lactitud;
        this.longitud = longitud;
        this.contratado = contratado;
    }
    public Oferente(Usuario usuario, String cedula, String nombre, String primerApellido, String nacionalidad, String telefono, String email, String lactitud, String longitud, int contratado, String direccion, byte[] curriculum, Set carateristicasoferentes, Set puestooferentes) {
       this.usuario = usuario;
       this.cedula = cedula;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.nacionalidad = nacionalidad;
       this.telefono = telefono;
       this.email = email;
       this.lactitud = lactitud;
       this.longitud = longitud;
       this.contratado = contratado;
       this.direccion = direccion;
       this.curriculum = curriculum;
       this.carateristicasoferentes = carateristicasoferentes;
       this.puestooferentes = puestooferentes;
    }
   
    public Integer getIdOferente() {
        return this.idOferente;
    }
    
    public void setIdOferente(Integer idOferente) {
        this.idOferente = idOferente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLactitud() {
        return this.lactitud;
    }
    
    public void setLactitud(String lactitud) {
        this.lactitud = lactitud;
    }
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    public int getContratado() {
        return this.contratado;
    }
    
    public void setContratado(int contratado) {
        this.contratado = contratado;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public byte[] getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(byte[] curriculum) {
        this.curriculum = curriculum;
    }
    public Set getCarateristicasoferentes() {
        return this.carateristicasoferentes;
    }
    
    public void setCarateristicasoferentes(Set carateristicasoferentes) {
        this.carateristicasoferentes = carateristicasoferentes;
    }
    public Set getPuestooferentes() {
        return this.puestooferentes;
    }
    
    public void setPuestooferentes(Set puestooferentes) {
        this.puestooferentes = puestooferentes;
    }




}


