package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2018 12:22:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private Integer idPuesto;
     private Empresa empresa;
     private String descripcion;
     private String sueldo;
     private String tipo;
     private int disponible;
     private Set puestooferentes = new HashSet(0);
     private Set carateristicaspuestos = new HashSet(0);

    public Puesto() {
    }

	
    public Puesto(Empresa empresa, String descripcion, String sueldo, String tipo, int disponible) {
        this.empresa = empresa;
        this.descripcion = descripcion;
        this.sueldo = sueldo;
        this.tipo = tipo;
        this.disponible = disponible;
    }
    public Puesto(Empresa empresa, String descripcion, String sueldo, String tipo, int disponible, Set puestooferentes, Set carateristicaspuestos) {
       this.empresa = empresa;
       this.descripcion = descripcion;
       this.sueldo = sueldo;
       this.tipo = tipo;
       this.disponible = disponible;
       this.puestooferentes = puestooferentes;
       this.carateristicaspuestos = carateristicaspuestos;
    }
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(String sueldo) {
        this.sueldo = sueldo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(int disponible) {
        this.disponible = disponible;
    }
    public Set getPuestooferentes() {
        return this.puestooferentes;
    }
    
    public void setPuestooferentes(Set puestooferentes) {
        this.puestooferentes = puestooferentes;
    }
    public Set getCarateristicaspuestos() {
        return this.carateristicaspuestos;
    }
    
    public void setCarateristicaspuestos(Set carateristicaspuestos) {
        this.carateristicaspuestos = carateristicaspuestos;
    }




}


