package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2018 12:22:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String userName;
     private String password;
     private String tipo;
     private Set oferentes = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String userName, String password, String tipo) {
        this.userName = userName;
        this.password = password;
        this.tipo = tipo;
    }
    public Usuario(String userName, String password, String tipo, Set oferentes, Set empresas) {
       this.userName = userName;
       this.password = password;
       this.tipo = tipo;
       this.oferentes = oferentes;
       this.empresas = empresas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getOferentes() {
        return this.oferentes;
    }
    
    public void setOferentes(Set oferentes) {
        this.oferentes = oferentes;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


