package domain;
// Generated 20/03/2018 10:03:47 AM by Hibernate Tools 4.3.1



/**
 * Carateristicaspuesto generated by hbm2java
 */
public class Carateristicaspuesto  implements java.io.Serializable {


     private Integer id;
     private Carateristicas carateristicas;
     private Puesto puesto;

    public Carateristicaspuesto() {
    }

    public Carateristicaspuesto(Carateristicas carateristicas, Puesto puesto) {
       this.carateristicas = carateristicas;
       this.puesto = puesto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carateristicas getCarateristicas() {
        return this.carateristicas;
    }
    
    public void setCarateristicas(Carateristicas carateristicas) {
        this.carateristicas = carateristicas;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }




}


