package domain;
// Generated 20/03/2018 10:03:47 AM by Hibernate Tools 4.3.1



/**
 * Carateristicasoferente generated by hbm2java
 */
public class Carateristicasoferente  implements java.io.Serializable {


     private Integer id;
     private Integer carateristicas;
     private Integer oferente;

    public Carateristicasoferente() {
    }

    public Carateristicasoferente(Integer carateristicas, Integer oferente) {
       this.carateristicas = carateristicas;
       this.oferente = oferente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCarateristicas() {
        return this.carateristicas;
    }
    
    public void setCarateristicas(Integer carateristicas) {
        this.carateristicas = carateristicas;
    }
    public Integer getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Integer oferente) {
        this.oferente = oferente;
    }


}


