package domain;
// Generated 20/03/2018 10:03:47 AM by Hibernate Tools 4.3.1



/**
 * Carateristicasoferente generated by hbm2java
 */
public class Carateristicasoferente  implements java.io.Serializable {


     private Integer id;
     private Carateristicas carateristicas;
     private Oferente oferente;

    public Carateristicasoferente() {
    }

    public Carateristicasoferente(Carateristicas carateristicas, Oferente oferente) {
       this.carateristicas = carateristicas;
       this.oferente = oferente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carateristicas getCarateristicas() {
        return this.carateristicas;
    }
    
    public void setCarateristicas(Carateristicas carateristicas) {
        this.carateristicas = carateristicas;
    }
    public Oferente getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Oferente oferente) {
        this.oferente = oferente;
    }




}


