package domain;
// Generated 20/03/2018 10:03:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Oferente generated by hbm2java
 */
public class Oferente  implements java.io.Serializable {


     private Integer idOferente;
     private Integer usuario;
     private String cedula;
     private String nombre;
     private String primerApellido;
     private String nacionalidad;
     private String telefono;
     private String email;
     private String lactitud;
     private String longitud;
     private int contratado;

    public Oferente() {
    }

	
    public Oferente(Integer usuario, String cedula, String nombre, String primerApellido, String nacionalidad, String telefono, String email, String lactitud, String longitud, int contratado) {
        this.usuario = usuario;
        this.cedula = cedula;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.nacionalidad = nacionalidad;
        this.telefono = telefono;
        this.email = email;
        this.lactitud = lactitud;
        this.longitud = longitud;
        this.contratado = contratado;
    }
   
    public Integer getIdOferente() {
        return this.idOferente;
    }
    
    public void setIdOferente(Integer idOferente) {
        this.idOferente = idOferente;
    }
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLactitud() {
        return this.lactitud;
    }
    
    public void setLactitud(String lactitud) {
        this.lactitud = lactitud;
    }
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    public int getContratado() {
        return this.contratado;
    }
    
    public void setContratado(int contratado) {
        this.contratado = contratado;
    }



}


