package domain;
// Generated 20/03/2018 10:03:47 AM by Hibernate Tools 4.3.1



/**
 * Puestooferente generated by hbm2java
 */
public class Puestooferente  implements java.io.Serializable {


     private Integer id;
     private Oferente oferente;
     private Puesto puesto;

    public Puestooferente() {
    }

    public Puestooferente(Oferente oferente, Puesto puesto) {
       this.oferente = oferente;
       this.puesto = puesto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Oferente getOferente() {
        return this.oferente;
    }
    
    public void setOferente(Oferente oferente) {
        this.oferente = oferente;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }




}


